Repository urdego/Urdego_Frontend, pull requests merged in 2024-12, with the labels that each got.

#15 Feat: workflows 삭제 및 pr 템플릿 추가
  .github/pull_request_template.md
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/main.yml
  .github/workflows/push-to-another-repo.yml
Labels: 📝 docs

#19 Fix/#18: 배포시 발생하는 로그인 관련 린트 오류 해결
  .github/ISSUE_TEMPLATE/📝-구현-목록-템플릿.md
  app/(auth)/login/page.tsx
Labels: 🐛 bug

#20 Feature/#13: 자동 배포를 위한 Github Actions 설정
  .github/workflows/git-push.yml
  app/api/auth/[...nextauth]/route.ts
  build.sh
Labels: ✨ feature

#21 Fix/#13: 자동 배포 대상 branch develop으로 변경
  .github/workflows/git-push.yml
Labels: 🐛 bug

#22 Fix/#13(revert): frok한 레파지토리 branch main으로 변경
  .github/workflows/git-push.yml
Labels: 🐛 bug

#23 Fix/#13: Github Actions 작동 테스트
  .github/pull_request_template.md
Labels: 🐛 bug

#24 Fix/#13: Github Actions 확인을 위한 2차 테스트
  app/(auth)/login/page.tsx
Labels: 🐛 bug

#25 Fix/#13: revert에 의해 대상 branch main으로 바뀐 것 develop으로 변경
  .github/workflows/git-push.yml
Labels: 🐛 bug
