Repository urdego/Urdego_Frontend, pull requests merged in 2025-01, with the labels that each got.

#26 Feature/#12 Apple Login 초기 설정 및 테스트
  app/(auth)/login/page.tsx
  app/api/auth/[...nextauth]/route.ts
  tsconfig.json
Labels: ✨ feature

#29 feat: Invalid redirect URL 해결을 위한 redirect_uri 명시
  app/api/auth/[...nextauth]/route.ts
Labels: 🐛 bug

#30 feat: callback url 쿠키 설정
  app/api/auth/[...nextauth]/route.ts
Labels: 🐛 bug, ✨ feature

#32 fix: 애플 로그인 redirect 에러 확인을 위한 로그 추가
  app/api/auth/[...nextauth]/route.ts
Labels: 🐛 bug, ✨ feature

#33 fix: 애플 로그인 디버깅 로그 추가
  app/api/auth/[...nextauth]/route.ts
Labels: 🐛 bug, ✨ feature

#34 feat: getAppleToken 호출 비동기 함수설정
  app/api/auth/[...nextauth]/route.ts
Labels: 🐛 bug, ✨ feature

#35 Feature/#12 login apple
  app/api/auth/[...nextauth]/route.ts
Labels: 🐛 bug, ✨ feature

#36 fix: 토큰 생성 확인용 로그 추가
  app/api/auth/[...nextauth]/route.ts
Labels: 🐛 bug, ✨ feature

#37 hotfix: invalid error로 인해 return 순서 변경
  app/api/auth/[...nextauth]/route.ts
Labels: 🐛 bug, ✨ feature

#40 feat: access token 확인을 위한 로그 추가
  app/api/auth/[...nextauth]/route.ts
Labels: ♻️ refactor

#31 Feat/#17: 이미지 최적화 구현(이미지 업로드하는 경우)
  app/(nav)/placeRegister/page.tsx
  app/api/content/compress/route.ts
  components/Layout/PlaceRegister/PlaceRegister.tsx
  hooks/placeRegister/useControlButtons.ts
  hooks/placeRegister/useControlInput.ts
  hooks/placeRegister/useRegisterFiles.ts
  package-lock.json
  package.json
Labels: ✨ feature

#51 Feat/#50: Skeleton UI 구현
  .github/ISSUE_TEMPLATE/📝-구현-목록-템플릿.md
  components/Common/Skeleton/LocationListSkeleton.tsx
  components/Common/Skeleton/Skeleton.styles.ts
  components/Common/Skeleton/Skeleton.tsx
  components/Layout/Home/LocationList/LocationList.styles.ts
  components/Layout/Home/LocationList/LocationList.tsx
  components/Layout/PlaceRegister/PlacePreview.styles.ts
  components/Layout/PlaceRegister/PlacePreview.tsx
  components/Layout/PlaceRegister/PlaceRegister.tsx
  hooks/placeRegister/useRegisterFiles.ts
  stores/loadingStore.ts
  stories/Common/LocationListSkeleton.stories.tsx
  stories/Common/Skeleton.stories.tsx
Labels: 🎨 design, 📝 docs, ✨ feature

#53 Feat/#49: 친구 초대 바텀시트 구현
  components/Layout/InviteUser/InviteUser.styles.ts
  components/Layout/InviteUser/InviteUser.tsx
Labels: 🎨 design, ✨ feature

#48 Feat/#28: 마이 페이지 UI 완성
  app/(nav)/myPage/accountCencellation/accountCencellation.styles.ts
  app/(nav)/myPage/accountCencellation/page.tsx
  app/(nav)/myPage/nicknameChange/nicknameChange.styles.ts
  app/(nav)/myPage/nicknameChange/page.tsx
  app/(nav)/myPage/page.tsx
  app/(nav)/myPage/passwordChange/page.tsx
  app/(nav)/myPage/passwordChange/passwordChange.styles.ts
  app/(nav)/myPage/simpleLoginSetting/page.tsx
  app/(nav)/myPage/simpleLoginSetting/simpleLoginSetting.styles.ts
  app/(nav)/myPage/soundSetting/page.tsx
  app/(nav)/myPage/soundSetting/soundSetting.styles.ts
  components/Common/AlertModal/AlertModal.styles.ts
  components/Common/AlertModal/AlertModal.tsx
  components/Common/CheckboxOption/CheckboxOption.styles.ts
  components/Common/CheckboxOption/CheckboxOption.tsx
  components/Common/OptionToggle/OptionToggle.styles.ts
  components/Common/OptionToggle/OptionToggle.tsx
  components/Layout/MyPage/ProfileInfo.styles.ts
  components/Layout/MyPage/SmallButton.styles.ts
  stories/Common/CheckboxOption.stories.tsx
  styles/Icon/check_circle.svg
  styles/Icon/circle.svg
  styles/Icon/sns-apple-login.svg
  styles/color/palette.ts
Labels: 🎨 design, ✨ feature

#57 Feat/#54: BottomSheet 공통 컴포넌트 분리
  components/Common/BottomSheet/BottomSheet.styles.ts
  components/Common/BottomSheet/BottomSheet.tsx
  components/Common/BottomSheet/LocationListBottomSheet.styles.ts
  components/Common/BottomSheet/LocationListBottomSheet.tsx
  hooks/bottomSheet/useBottomSheet.ts
Labels: ♻️ refactor

#60 Feat: 타입 정의 이동 및 세션 관리 추가
  app/api/auth/[...nextauth]/route.ts
  lib/auth/refreshToken.ts
  lib/types/next-auth.d.ts
Labels: ♻️ refactor

#62 Feat/#59: 장소 등록 및 조회 서버 연결 구현
  app/api/content/[userId]/route.ts
  app/api/content/route.ts
  config/apiEndPointConfig.ts
  hooks/locationList/useGetInfiniteLocationList.ts
  hooks/placeRegister/useRegisterFiles.ts
  hooks/placeRegister/useUploadFiles.ts
  next.config.mjs
Labels: ✨ feature, ♻️ refactor

#65 Hotfix/#59: 'API_BASE_URL' is not exported from '@/config/apiEndPointConfig' 해결
  app/api/game/route.ts
  app/api/invite/route.ts
  app/api/login/route.ts
  app/api/makeRoom/route.ts
  app/api/nickname/route.ts
  app/api/notification-service/connect/[userId]/route.ts
  app/api/signup/route.ts
  app/metadata.ts
  config/apiEndPointConfig.ts
  public/favicon-outline.svg
Labels: 🐛 bug

#64 hotfix: ReadyToast Storybook Typecheck Error 해결
  stories/Layout/WaitingRoom/ReadyToast.stories.tsx
Labels: 🐛 bug

#66 Hotfix: useUserSotre에 존재하지 않는 userId 부분 주석처리
  hooks/locationList/useGetInfiniteLocationList.ts
Labels: 🐛 bug

#68 Fix/#67: useSSEConnection 제거
  hooks/useSSEConnection.ts
Labels: 🐛 bug, ✨ feature

#69 Hofix: Button Type Error 해결
  app/api/auth/[...nextauth]/route.ts
  stories/Layout/WaitingRoom/ReadyToast.stories.tsx
Labels: 🐛 bug

#71 Feat/#70: 1차 MVP README 작성 완료
  README.md
Labels: 📝 docs

#73 Feat/#61 소셜로그인 백엔드 연동 및 사용자 상태관리
  app/api/auth/[...nextauth]/route.ts
  lib/types/next-auth.d.ts
  stores/useUserStore.ts
Labels: ✨ feature

#74 Hotfix: useUserStore 변경에 따른 일부 페이지 store 값 변경
  app/(nav)/home/page.tsx
Labels: 🐛 bug

#72 Feat/#55 : 컨텐츠 추가 바텀시트 컴포넌트 UI구현 1차 완료 했습니다.
  components/Layout/AddContents/AddContents.styles.ts
  components/Layout/AddContents/AddContents.tsx
  styles/Icon/search-btn.svg
Labels: 🎨 design, ✨ feature

#77 Feat/#76 kakao login type 구조 변경
  app/api/auth/[...nextauth]/route.ts
  lib/types/next-auth.d.ts
Labels: 🐛 bug

#78 Feat/#76 Login Provider 별 데이터 타입 수정
  app/api/auth/[...nextauth]/route.ts
  lib/types/next-auth.d.ts
Labels: 🐛 bug

#79 Fix: undefined일 시 빈 문자열 리턴
  app/api/auth/[...nextauth]/route.ts
Labels: 🐛 bug

#82 Feat/#81 소셜로그인 Callback Issue 해결
  app/api/auth/[...nextauth]/route.ts
Labels: ✨ feature

#87 Feat/#63: 컨텐츠 조회 최적화
  components/Common/BottomSheet/LocationListBottomSheet.styles.ts
  components/Common/BottomSheet/LocationListBottomSheet.tsx
  components/Common/LoadingSpinner/DotLoadingSpinner.styles.ts
  components/Common/LoadingSpinner/DotLoadingSpinner.tsx
  components/Layout/Home/LocationList/LocationList.tsx
  components/Layout/PlaceRegister/PlacePreview.tsx
  hooks/locationList/useGetInfiniteLocationList.ts
Labels: ✨ feature, ♻️ refactor

#93 Feat/#85 마이페이지 API 통신 처리
  app/(nav)/myPage/nicknameChange/page.tsx
  app/(nav)/myPage/page.tsx
  app/api/nickname/route.ts
  app/api/userInfo/route.ts
  components/Layout/MyPage/ProfileButton.styles.ts
  components/Layout/MyPage/ProfileButton.tsx
  components/Layout/MyPage/ProfileInfo.tsx
  components/Layout/MyPage/SmallButton.tsx
  config/apiEndPointConfig.ts
Labels: 🎨 design, ✨ feature

#90 Feat/#89: 미리보기 이미지 수 우선적으로 증가 구현 및 메타 데이터 추출 개선
  hooks/placeRegister/useRegisterFiles.ts
Labels: ♻️ refactor

#95 hotfix: 로그인 POST 데이터 타입 변경
  app/api/auth/[...nextauth]/route.ts
Labels: ♻️ refactor

#96 hotfix: 로그인 데이터 타입 변경
  app/api/auth/[...nextauth]/route.ts
Labels: ♻️ refactor

#97 hotfix: useGetInfiniteLocationList의 로직 변경에 따라 addContents 로직도 변경했습니다.
  components/Layout/AddContents/AddContents.tsx
Labels: 🐛 bug

#99 HotFix: vervel storybook 관련 오류 발생 storybook 삭제
  stories/Layout/Mypage/SettingButton.stories.tsx
  stories/Layout/Mypage/SmallButton.stories.tsx
Labels: 🐛 bug

#100 fix: vercel 배포 오류 발생 rapi/invite관련 로직 삭제
  app/api/invite/route.ts
  components/Layout/MakeRoom/FriendsInviteForm.tsx
Labels: 🐛 bug
