Repository urdego/Urdego_Frontend, pull requests merged in 2025-03, with the labels that each got.

#167 feat: Email, CharacterType 전역 상태 관리 추가
  app/(auth)/login/page.tsx
  app/(nav)/myPage/page.tsx
  app/api/auth/[...nextauth]/route.ts
  hooks/character/useCharacterState.ts
  stores/useUserStore.ts
Labels: ♻️ refactor

#169 feat: icon, screenshot image 변경
  public/Icon/icon.png
  public/Icon/icon_152.png
  public/Icon/icon_180.png
  public/Screenshots/preview-01.png
  public/Screenshots/preview-02.png
  public/Screenshots/preview-03.png
  public/Splash/splash.json
  public/icon.png
  public/icon_128.png
  public/icon_192.png
  public/icon_384.png
  public/icon_512.png
  public/manifest.json
  public/screenshots/01.svg
  public/screenshots/02.svg
  public/screenshots/03.svg
  public/screenshots/04.svg
  public/sitemap-0.xml
  public/sw.js
  public/sw.js.map
  public/workbox-4754cb34.js
  public/workbox-e43f5367.js
  public/workbox-e43f5367.js.map
Labels: ✨ feature

#170 Feat/#168 middleware 및 manifest 일부 수정
  middleware.ts
  public/Icon/icon_512.png
  public/Icon/maskable_icon.png
  public/Icon/maskable_icon_128.png
  public/Icon/maskable_icon_512.png
  public/manifest.json
  public/sitemap-0.xml
  public/sw.js
  public/sw.js.map
  public/workbox-4754cb34.js
  public/workbox-e43f5367.js
  public/workbox-e43f5367.js.map
Labels: 🐛 bug

#175 Style/#173 온보딩/홈/인게임 등 UI 변경 요청사항 반영
  app/(auth)/login/Login.styles.ts
  app/commonPage.styles.ts
  app/game/[roomId]/[round]/layout.tsx
  app/game/[roomId]/[round]/page.tsx
  app/game/[roomId]/[round]/roundRank/page.tsx
  app/game/[roomId]/waitingRoom/page.tsx
  app/onBoarding.styles.ts
  app/page.tsx
  components/Common/NavBar/NavBar.styles.ts
  components/Common/NavBar/NavBar.tsx
  components/Common/NavBar/NavIcon.tsx
  components/Layout/Game/MapBottomSheet.styles.ts
  components/Layout/Game/MapBottomSheet.tsx
  components/Layout/Game/ProgressBar.styles.ts
  components/Layout/Game/RankList.tsx
  components/Layout/Home/Character/CharacterBottomSheet.styles.ts
  components/Layout/Home/HomeBox/HomeBox.styles.ts
  components/Layout/Home/HomeBox/Level.styles.ts
  components/Layout/Home/HomeBox/Level.tsx
  hooks/websocket/useWebsocketFunctions.ts
  public/sw.js.map
  public/workbox-4754cb34.js
  stores/useAudioStore.ts
  styles/Icon/Home.svg
  styles/Icon/HomeColor.svg
  styles/Icon/Map.svg
  styles/Icon/MapColor.svg
  styles/Icon/Mypage.svg
  styles/Icon/MypageColor.svg
  styles/Icon/Navbar/Home.svg
  styles/Icon/Navbar/HomeColor.svg
  styles/Icon/Navbar/Map.svg
  styles/Icon/Navbar/MapColor.svg
  styles/Icon/Navbar/Mypage.svg
  styles/Icon/Navbar/MypageColor.svg
  styles/color/palette.ts
Labels: 🎨 design, ✨ feature, ♻️ refactor

#177 Refactor/#176 로그인 시 userId, email 전역관리 Session으로 변경
  app/(auth)/login/page.tsx
  app/(nav)/home/page.tsx
  public/sitemap-0.xml
  public/sw.js.map
Labels: ♻️ refactor

#185 Docs/#184 urdego App Privacy Policy 문서 제출
  AppPrivacyPolicy.html
Labels: 📝 docs

#189 Refactor/#187 ingame ux
  app/game/[roomId]/[round]/layout.tsx
  app/game/[roomId]/[round]/page.tsx
  components/Common/NavBar/NavBar.styles.ts
  components/Layout/Game/GoogleMap.tsx
  components/Layout/Game/MapBottomSheet.styles.ts
  components/Layout/Game/MapBottomSheet.tsx
  components/Layout/Game/Swiper.tsx
  components/Layout/Home/HomeBox/Level.tsx
  public/sw.js.map
Labels: ♻️ refactor

#190 Feat/#183 waiting room insert
  app/game/[roomId]/waitingRoom/page.tsx
  components/Common/NavBar/NavBar.styles.ts
  components/Common/NavBar/NavBar.tsx
  components/Layout/AddContents/AddContents.styles.ts
  components/Layout/InviteUser/InviteUser.tsx
  components/Layout/WaitingRoom/PositionCard.styles.ts
  components/Layout/WaitingRoom/PositionCard.tsx
Labels: 🐛 bug, 🎨 design, ✨ feature

#194 Feat/#193 대기방 리스트에서 대기방으로 들어가는 기능
  app/waitingRoomList/page.tsx
  components/Common/RoomButton/RoomButton.tsx
  components/Common/RoomButton/RoomButtonList.tsx
Labels: ✨ feature

#165 Feat/#128: 모바일 환경의 장소 등록하기 화면에서 메타 데이터 추출 및 이미지 업로드 문제 해결
  .github/workflows/vercel-preview.yml
  app/(nav)/content/register/layout.tsx
  capacitor.config.ts
  components/Common/BottomSheet/ContentRegisterBottomSheet.styles.ts
  components/Common/BottomSheet/ContentRegisterBottomSheet.tsx
  components/Common/RoomButton/RoomButton.styles.ts
  components/Layout/ContentRegister/ContentRegisterIcon.tsx
  components/Layout/ContentRegister/InputCard.styles.ts
  components/Layout/LocationRegister/GoogleMap.tsx
  config/apiEndPointConfig.ts
  hooks/contentRegister/useConvertLocationToAddress.ts
  hooks/contentRegister/useRegisterFiles.ts
  hooks/contentRegister/useUploadFiles.ts
  hooks/waitingRoomList/useGetWaitingRoomList.ts
  next.config.mjs
  package-lock.json
  package.json
  public/sw.js.map
Labels: 🐛 bug, ♻️ refactor

#204 Feat/#201 소셜로그인 탈퇴 로직 수정
  app/api/auth/withdraw/route.ts
  lib/auth/refreshToken.ts
Labels: ✨ feature, ♻️ refactor

#207 Feat/#195-대기방, 마이페이지 잡다한 에러 해결
  app/game/[roomId]/waitingRoom/page.tsx
  app/game/[roomId]/waitingRoom/waitingRoom.styles.ts
  components/Common/Toast/AlertToast.styles.ts
  components/Common/TopBar/TopBar.styles.ts
  components/Layout/AddContents/AddContents.tsx
  components/Layout/InviteUser/InviteUser.styles.ts
  components/Layout/InviteUser/InviteUser.tsx
  components/Layout/InviteUser/UserListItem.tsx
  components/Layout/MyPage/ProfileInfo.tsx
  components/Layout/MyPage/ProfileInfoSkeleton.styles.ts
  styles/Icon/clear-btn.svg
Labels: 🐛 bug

#208 Fix/#205 출시 후 게임 관련 이슈 해결
  app/game/[roomId]/[round]/layout.tsx
  app/game/[roomId]/[round]/page.tsx
  components/Layout/Home/HomeBox/Level.tsx
  public/sw.js.map
Labels: 🐛 bug, ♻️ refactor

#211 Refactor/# 210 my page lighthouse 점수 기준 성능 개선
  app/(nav)/myPage/MyPageClient.tsx
  app/(nav)/myPage/page.tsx
  app/api/auth/[...nextauth]/route.ts
  components/Layout/MyPage/ProfileInfo.tsx
  hooks/character/useCharacterData.ts
  lib/auth/authOptions.ts
  styles/Icon/Character/angularMin.png
  styles/Icon/Character/basicMin.png
  styles/Icon/Character/bumphyMin.png
  styles/Icon/Character/dotMin.png
  styles/Icon/Character/planetMin.png
  styles/Icon/Character/sharpMin.png
  styles/Icon/Character/squareMin.png
  styles/Icon/Character/starMin.png
  styles/Icon/Character/woolMin.png
Labels: ♻️ refactor
