Repository urdego/Urdego_Frontend, pull requests merged in 2025-02, with the labels that each got.

#105 Hotfix: 캐릭터 변경으로 인한 파일경로 변경
  components/Layout/Game/Character.tsx
  components/Layout/WaitingRoom/PositionCard.tsx
Labels: 🐛 bug

#106 Fix: Lottie 및 GLTFLoader import 에러 해결
  components/Common/LoadingSpinner/LoadingSpinner.tsx
  components/Layout/Home/Character/UserCharacter.tsx
  tsconfig.json
Labels: 🐛 bug

#107 Fix: GLTF 모듈 불러오는 방식 수정
  components/Layout/Home/Character/UserCharacter.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: 🐛 bug

#108 fix: ChannelButton 스토리 제거
  stories/Layout/Home/ChannelButton.stories.ts
Labels: 🐛 bug

#109 fix: GLTF 파일명 - public 파일명 URL 경로 문제 해결
  components/Layout/Home/Character/UserCharacter.tsx
Labels: 🐛 bug

#112 Feature/#94 : SEO 반영
  components/Layout/MakeRoom/FriendsInviteForm.tsx
  next-sitemap.config.js
  next.config.mjs
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
Labels: ✨ feature

#115 Hitfix: sitemap 명시 배포 도메인 수정
  next-sitemap.config.js
Labels: 🐛 bug

#125 Feat/#116-watingroom UI 세팅완료
  app/game/[roomId]/waitingRoom/page.tsx
  app/game/[roomId]/waitingRoom/waitingRoom.styles.ts
  components/Common/Button/Button.styles.ts
  components/Common/Button/Button.tsx
  components/Common/SearchBar/SearchBar.styles.ts
  components/Common/SearchBar/SearchBar.tsx
  components/Layout/AddContents/AddContents.styles.ts
  components/Layout/AddContents/AddContents.tsx
  components/Layout/InviteUser/InviteUser.styles.ts
  components/Layout/InviteUser/InviteUser.tsx
  components/Layout/WaitingRoom/PositionCard.styles.ts
  components/Layout/WaitingRoom/PositionCard.tsx
  components/Layout/WaitingRoom/WButton.styles.ts
  components/Layout/WaitingRoom/WButton.tsx
  styles/Icon/contentsBox.png
  styles/Image/WaitingRoom/BackgroundImage.png
  styles/Image/WaitingRoom/BackgroundImageL.png
  styles/color/palette.ts
Labels: 🎨 design, ✨ feature

#119 Feature/#91: 대기방 리스트 화면 UI 구현 및 서버 연결
  app/(nav)/groupList/page.tsx
  app/(nav)/home/page.tsx
  app/(nav)/waitingRoomList/page.tsx
  app/(nav)/waitingRoomList/waitingRoomList.styles.ts
  app/api/waitingRoomList/route.ts
  app/commonPage.styles.ts
  components/Common/LoadingSpinner/DotLoadingSpinner.styles.ts
  components/Common/LoadingSpinner/DotLoadingSpinner.tsx
  components/Common/NavBar/NavBar.tsx
  components/Common/RoomButton/RoomButton.styles.ts
  components/Common/RoomButton/RoomButton.tsx
  components/Common/RoomButton/RoomButtonIcon.tsx
  components/Common/RoomButton/RoomButtonList.tsx
  components/Common/RoomButton/WaitingRoomListIcon.tsx
  config/apiEndPointConfig.ts
  hooks/waitingRoomList/useGetWaitingRoomList.ts
  lib/types/character.ts
  styles/Icon/Person.svg
  styles/Icon/waitingRoomList/Person.svg
  styles/Icon/waitingRoomList/Refresh.svg
  styles/Image/WaitingRoomList/Background_FullHill.png
  styles/Image/WaitingRoomList/Background_OnlyHill.png
Labels: ✨ feature

#134 Feat/#130-waitingroom UI 수정 및 빌드 디버깅
  app/game/[roomId]/waitingRoom/page.tsx
  app/game/[roomId]/waitingRoom/waitingRoom.styles.ts
  components/Common/AlertModal/AlertModal.styles.ts
  components/Common/AlertModal/AlertModal.tsx
  components/Common/RoomButton/WaitingRoomListIcon.tsx
  components/Layout/AddContents/AddContents.styles.ts
  components/Layout/AddContents/AddContents.tsx
  components/Layout/InviteUser/InviteUser.styles.ts
  components/Layout/InviteUser/InviteUser.tsx
  components/Layout/WaitingRoom/PositionCard.styles.ts
  components/Layout/WaitingRoom/PositionCard.tsx
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  stories/Common/RoomButton.stories.tsx
  styles/Image/WaitingRoom/WRoomAssistance.png
Labels: 🎨 design, ✨ feature

#135 Feat/#126-websocket 연결
  app/(nav)/home/page.tsx
  hooks/websocket/useWebsocketFunctions.ts
  stores/types/websocket.ts
  stores/useWebSocketStore.ts
Labels: ✨ feature

#137 Feature/#136 방만들기 bottom sheet 구현했습니다.
  app/(nav)/home/page.tsx
  app/(nav)/waitingRoomList/page.tsx
  app/(nav)/waitingRoomList/waitingRoomList.styles.ts
  app/api/auth/withdraw/route.ts
  app/game/[roomId]/waitingRoom/page.tsx
  app/game/[roomId]/waitingRoom/waitingRoom.styles.ts
  components/Common/Toast/AlertToast.styles.ts
  components/Common/Toast/AlertToast.tsx
  components/Layout/MakeRoom/CreateRoomBottomSheet.styles.ts
  components/Layout/MakeRoom/CreateRoomBottomSheet.tsx
  stores/useWebSocketStore.ts
  styles/Icon/Toast/alert.svg
Labels: 🎨 design, ✨ feature

#139 Feat/#123 User-service API 변경사항 반영
  app/(nav)/myPage/page.tsx
  app/api/character/route.ts
  app/api/userInfo/route.ts
  app/game/[roomId]/[round]/roundRank/page.tsx
  components/Layout/Game/RankList.tsx
  components/Layout/Home/Character/SuccessToast.tsx
  components/Layout/Home/HomeBox/HomeBox.tsx
  components/Layout/Home/HomeBox/Level.styles.ts
  components/Layout/Home/HomeBox/Level.tsx
  components/Layout/MyPage/ProfileInfo.tsx
  config/apiEndPointConfig.ts
  hooks/character/useCharacterState.ts
Labels: ✨ feature, ♻️ refactor

#140 Refactor/#132 사용자 별 캐릭터 타입 Google Map Marker 연동
  app/(nav)/home/page.tsx
  components/Layout/Game/GoogleMap.tsx
  components/Layout/LocationRegister/GoogleMap.tsx
  hooks/character/useCharacterMarker.ts
  hooks/character/useCharacterState.ts
Labels: ✨ feature, ♻️ refactor

#144 Feature/#138 방 만들기 소켓 로직 구현
  app/(nav)/waitingRoomList/page.tsx
  app/(nav)/waitingRoomList/waitingRoomList.styles.ts
  app/api/makeRoom/route.ts
  app/game/[roomId]/waitingRoom/page.tsx
  components/Layout/MakeRoom/CreateRoomBottomSheet.styles.ts
  components/Layout/MakeRoom/CreateRoomBottomSheet.tsx
  components/Layout/WaitingRoom/PositionCard.styles.ts
  components/Layout/WaitingRoom/PositionCard.tsx
  config/apiEndPointConfig.ts
  hooks/websocket/useWebsocket.types.ts
  hooks/websocket/useWebsocketFunctions.ts
  stores/useGameStore.ts
  stores/useGameStores.ts
Labels: 🐛 bug, 🎨 design, ✨ feature

#148 Feat/#122: 장소 등록하기 화면 border, 커스텀 toast 적용
  app/api/content/route.ts
  app/content/page.tsx
  components/Common/Skeleton/Skeleton.styles.ts
  components/Common/Toast/LoadingToast.tsx
  components/Layout/ContentRegister/ImagePreview.styles.ts
  components/Layout/ContentRegister/ImageUpload.styles.ts
  components/Layout/ContentRegister/InputCard.styles.ts
  components/Layout/ContentRegister/LocationSearchButton.styles.ts
  components/Layout/ContentRegister/LocationSearchButton.tsx
  components/Layout/TipModal/TipModal.styles.ts
  hooks/contentRegister/useRegisterFiles.ts
  hooks/contentRegister/useUploadFiles.ts
Labels: 🎨 design, ♻️ refactor

#159 Feat/143 인게임 소켓 통신 구현
  app/(nav)/home/page.tsx
  app/api/game/route.ts
  app/game/[roomId]/[round]/page.tsx
  app/game/[roomId]/[round]/roundRank/page.tsx
  app/game/[roomId]/waitingRoom/page.tsx
  components/Layout/Game/GoogleMap.tsx
  components/Layout/Game/RankList.styles.ts
  components/Layout/Game/RankList.tsx
  components/Layout/Game/Swiper.tsx
  config/apiEndPointConfig.ts
  config/webSocketConfig.ts
  hooks/websocket/useWebsocketFunctions.ts
  lib/types/inGame.ts
  lib/types/notification.ts
  lib/types/roomJoin.ts
  lib/types/websocket.ts
  stores/useGameStore.ts
  styles/Icon/Game/Rank/Rank4.svg
  styles/Icon/Game/Rank/Rank5.svg
  styles/Icon/Game/Rank/Rank6.svg
  styles/Icon/Game/Rank/icon/icon-rank.svg
Labels: ✨ feature, ♻️ refactor
